.gitmodules

hi, git clone recursive give me this error, because of using ssh nor https for url
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists. fatal: clone of 'git@github.com:espressif/esp-protocols.git' into submodule path 'C:/.../ESP32-Daikin/ESP32-Daikin/esp-protocols' failed

url for esp-protocols - ssh to https

---

main/Faikin.c

Original timeout value appears too small, long packets aren't received. Bump up to 500 ticks, introduce a macro to prevent errors (note 10 instead of 100 in one location)
Faikin now works with my AC.

main/Faikin: Increase serial timeout

---

main/Faikin.c

Fix a sad typo, which caused temperature reporting to malfunction. Added also err=0 for full completeness. Verified against my original BRP module on a second aircon.

main/Faikin: Fix typo in web_get_sensor_info

---

faikin-s21.c
main/Faikin.c

Fix update of the switch state on the web page. Add option to S21 simulator for easy testing

main/Faikin.c: Fix missing "powerful" state update

---

ESP32/main/daikin_s21.h

Fix a gross typo; the value to check against should be ETX

main/daikin_s21: Fix checksum escaping

---

ESP32/main/Faikin.c
ESP32/main/daikin_s21.h

Rewrite daikin_s21_response() to only check against minimum required
payload length. In case of a mismatch, an error message will be emitted
over MQTT.
Dump partially received data in "timeout" messages; this may help to pinpoint
where exactly the error occurs
These changes make S21 implementation more robust and ease debugging
Signed-off-by: Pavel Fedin <pavel_fedin@mail.ru>

More robust S21

---

ESP32/main/Faikin.c

Fixes "unused function" warning if ELA is not defined

main/Faikin: Put addNote() under #ifdef ELA

---

Tools/faikin-s21.c

I was getting compiler type warnings when building `faikin-s21.c`.
This fixed it.

Fix for incorrect type for s21_nak()

---

Tools/Makefile
Tools/faikin-s21.c

These changes allowed me to build the `faikin-s21` Simulator Tool on both Mac and Linux.
I have done these as a series of commits to make the PR easier to breakdown:
- Allow building tools that don't depend on MySQL, if MySQL isn't installed
- Use the `brew --prefix` command to find Homebrew - rather than assuming `libpopt` is at specific path
- Fix for `daikin_s21.h` search path - I am not sure why `main` was both in the `#include` path and search path
- Added missing includes / libm that are needed to build on Linux

S21 simulator build fixes

---

ESP32/build.bat

Our build uses some auxiliary tools, which are also built from C sources in the process. Unfortunately Windows version of ESP32-IDF decided to ditch MinGW, and comes with a naked Windows cmd.exe shell with a minimalist set of tools (idf.py, git, and that's all). It's not possible to run idf.py from e. g. MinGW prompt; it doesn't allow doing that.
Our auxiliary tools require a full POSIX environment with gcc and make.
Work around IDF limitations by introducing a bridge script, which relies on a side-by-side installation of a POSIX environment, such as MSYS or Cygwin. Our auxiliary tools are now run via that environment, while idf.py keeps living in pure Windows, as it wants.

ESP32: Introduce build.bat for use under Windows

---

ESP32/release/README.md

Added note for different bootloader addresses. I found that the address for the S3 chip on the newer models is different than for the S1 (https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/bootloader.html).

Update release falsh README.md to include note for different bootloader addresses.

---

ESP/main/Faikin.c

I added the device_class property for the energy measurement so it can be used in the Home Assistant energy dashboard. 
Without it you see this error message:

Set device_class property to "energy" for the Lifetime energy entity

---

ESP/main/Faikin.c
ESP/main/cn_wired_driver.c

Found a problem with new RMT driver, which doesn't allow us to properly specify tx idle state as high. Worked around by using line inversion. Fixed internal status handling. CN_WIRED verified to work with simulator with the following settings:
nox21 = true
nox50a = true
nocnwired = false
noas = true
noswaptx = true
noswaprx = true
Protocols other than cn_wired disabled for speed; autodetection is expected to work. Inversion is disabled because my development board has non-inverted outputs. Autodetection should work after all previous fixes, but untested.

Attempt at fixing CN_WIRED transmission

---

ESP/setbuildsuffix.bat

Technically belongs to RevK library, but just convenient to have in top-level project directory. Similar to build.bat, runs setbuildsuffix script via POSIX environment

ESP: setbuildsuffix wrapper for Windows

---

ESP/main/Faikin.c

Since we cannot elicit any response from the AC, we cannot know whether tx alone has correct polarity or not. Let's only invert all or nothing, thus rx polarity (which can be detected) would also determine tx polarity

main/Faikin: Forbid different rx and tx polarities for CN_WIRED

---

ESP/main/Faikin.c
ESP/main/cn_wired_driver.c

- Adjust signal_range_max_ns, so that we don't wait for too long
- Sleep 20 ms between receiving a packet and sending our packet.
This ensures that the packet we send falls in between packets AC sends to us. The same algorithm works on 8266.

ESP/main: Tweak CN_WIRED rx/tx timings

---

ESP/main/Faikin.c

Some fixes for loopback mode. Flaws discovered during protocol reverse-engineering process. A legitimate 'M' command was found, which caused false positive, disrupting comms.

Loopback fixes

---

ESP/Makefile

Only "ours" modules need to be updated to tips on "make update". Proper versions of nested submodules is determined by their parents, who store super-pointers individually.

ESP/Makefile: Update only top-level modules to new versions

---

ESP/main/daikin_s21.h
Tools/Simulators/faikin-s21.c

Added commands to support protocol v2, as expected by BRP069B41. Successfully goes online. More comments for what has been figured out.

Simulators/faikin-s21: Protocol v2 support

---

Manuals/Setup.md

This PR refines the instructions for re-flashing the firmware on ESP32 devices. Key updates include:
- Improved clarity and accuracy: Rewrote the instructions to ensure they are easy to follow and free of ambiguities.
- Updated links and resources: Verified and included relevant links for downloading firmware binaries and purchasing required hardware.
These changes aim to enhance the user experience and reduce potential errors during the re-flashing process.

Refactored firmware re-flashing instructions

---

ESP/main/Faikin.c

We may still want F3 for debug or testing via injection; make sure "powerful" state isn't clobbered

main/Faikin: Improve F3 robustness

---

ESP/main/Faikin.c

Stop polling F8 (protocol version) and FC (model) after getting a response once. These values are properties of the A/C and do not change, no need to waste time polling them repeatedly.
Fixed masking shield bits in F8, pv= is now always correct.

main/Faikin: Do not poll immutable values continuously

---

ESP/main/Faikin.c

Revert https://github.com/revk/ESP32-Faikin/commit/43650e68741bb11a850de4bb6dc8418676f4141f to track `HVACAction.IDLE` in HA (with Faikin auto mode and `nohvacaction` option disabled)

Track HVAC_IDLE for Faikin auto mode in HA

---

ESP/main/Faikin.c
ESP/settings.def

It turns out that our legacy API isn't completely properly done; and it appears to disrupt Daikin app's advanced functionality (like power saving modes), causing it to crash.
Let's mitigate that by introducing a setting, which allows for enable or disable auto-discovery on demand. Defaults to off since the feature is currently experimental.

ESP: Introduce udp_discovery setting
