revk/ESP32-Faikin

- main/Faikin.c
Add URLs, compatible with original BRP controller, according to OpenHAB source code. Enough for OH to use Faikin as a drop-in replacement for an original Daikin online controller.
> main/Faikin: More status and control URLs

- Makefile
- faikin-s21.c
- main/Faikin.c
- main/daikin_s21.h
- main/faikin_enums.h
Tested against my Daichi cloud controlled and my FTXF20D AC unit. Quirks documented. Some #define's and protocol-specific encoding/decoding funcs factored out to .h files, to eliminate copypastes and make sure the same thing is used everywhere.
> S21 simulator

- ESP32/main/Faikin.c
Fan swing control now works via Daikin API.
> main/Faikin: Add forgotten "f_dir" Daikin control

- ESP32/main/Faikin.c
I hope you won't mind add some verbose comments to the code. I made them for myself for better understanding of how the code works. Keeping them in sync would allow me for smoother diff-ing against your repo.
> Esp8266 changes for upstream

- ESP32/main/Faikin.c
No more long repeated fragments like "prototype(proto)" and "protoname[prototype(proto)]". Proper available set of fan speeds for all 3 supported protocols.
Backport from ESP8266
> Tidy up protocols and their properties

- ESP32/main/Faikin.c
- ESP32/main/faikin_enums.h
- ESP32/settings.def
Hello! I'd like to offer back some refactors which i made. They helped me with code upgrade and CN_WIRED implementation
> Some refactors from 8266 port

- ESP/main/Faikin.c
Factor out a common routine and use it. CN_WIRED step is 1C. The issue reported in
https://github.com/Sonic-Amiga/ESP8266-Faikin/issues/15#issuecomment-2193151580
> main/Faikin: Report correct temperature step for HomeAssistant

- ESP/main/Faikin.c
Using a term "report" (meaning AC -> user) helps to easier distinguish these functions from daikin_set_xxx, which "set" (meaning user -> AC) control values. Helps reading the code and avoid confusing what is what.
> main/Faikin: Rename set_xxx to report_xxx

- ESP/main/CMakeLists.txt
- ESP/main/Faikin.c
- ESP/main/cn_wired.h
- ESP/main/cn_wired_driver.c
- ESP/main/cn_wired_driver.h
1. Extract the driver to a replace-able file, akin to 8266 port. The purpose is code unification.
2. Fix re-initialization, now works correctly
> Introduce CN_WIRED driver and fix bug

- ESP/main/Faikin.c
- ESP/main/cn_wired.h
- ESP/main/cn_wired_driver.c
- ESP/main/cn_wired_driver.h
- ESP/main/faikin_enums.h
- Better (i hope) structured CN_WIRED protocol code
- Proper fan speed and swing controls
> Remaining changes from ESP8266 port

- ESP/main/cn_wired_driver.c
Spent some time on understanding WTH is going on. Let's leave some verbose notes on this tricky question.
> main/cn_wired_driver: Better comment on SYNC trick

- ESP/main/Faikin.c
Was occasionally lost in a51247577471d1f00d1d971c85ed9848f3dac3b5
> main/Faikin: Bring back CN_WIRED led control

- ESP/main/Faikin.c
C_WIRED uses 3 speeds + auto + quiet (which is called "night" in S21). Our user interface works with that correctly, but HA interface won't understand "quiet". Fix that.
> main/Faikin: Proper HA fan modes for CN_WIRED

- ESP/main/Faikin.c
Returned by command FC, reverse engineered from BRP069B41
> main/Faikin: Support S21 model code

- .gitignore
- Tools/Simulators/Makefile
- Tools/Simulators/faikin-s21.c
- Tools/Simulators/faikin-s21.h
- Tools/Simulators/faikin-x50.c
- Tools/Simulators/osal.c
- Tools/Simulators/osal.h
- Tools/Simulators/s21-control.c
- More known commands, even more unknown
- s21-control tool, which communicates to the sim via shared memory and allows for changing values in real time. Sorry, only works on Windows at the moment (because that's my OS). Feel free to implement UNIX functionality using posix shmem; calls map 1:1 very well. I can do it and test under Cygwin, but later.
> Big update for S21 sim

- ESP/main/Faikin.c
We could be probing commands using "send" mqtt message; and in this case it's a nice idea to see responses on "rx" topic, even if the response consists of a single ack/nak
Simplifies testing protocol a lot.
> main/Faikin: Explicitly dump ACK/NAK if b.dumping is on

- ESP/main/Faikin.c
Now fully works on FTXF20D5V1B.
> main/Faikin: Fix "powerful" mode

- ESP/main/Faikin.c
- Implement discovery responder. Now "Daikin online controller" app sees us
- Implement some get_model_info parameters. "Daikin online controller" app now gives us extra controls for special modes.
The purpose of this change is to aid reverse engineering and improve compatibility with apps, using Daikin API.
> Improve Daikin API support

- ESP/main/daikin_s21.h
- Tools/Simulators/faikin-s21.c
- Tools/Simulators/faikin-s21.h
- Tools/Simulators/faikin-x50.c
- Tools/Simulators/osal.c
- Tools/Simulators/osal.h
- Tools/Simulators/s21_state_parser.c
Tested on Cygwin. Fully works, including shared memory.
> Fix UNIX build of S21 Simulator

- Tools/Simulators/Makefile
- Tools/Simulators/README.md
- Tools/Simulators/faikin-x50.c
Fix Simulator build for Apple Silicon and add note to Readme
> Fix Simulator build for Apple Silicon and add note to Readme

- ESP/main/Faikin.c
- ESP/settings.def
Fix https://github.com/revk/ESP32-Faikin/issues/482
⚠️ not tested
> Add an option to control LED on Faikin auto mode based on HVAC action
